name = "blockless-codelabs"
version = "1.0.0"
type = "site"
content_type = "html"

[deployment]
nodes = 1

[build]
dir = ".bls"
public_dir = "docs"
entry = "blockless-codelabs_debug.wasm"
command = "npm run build"

[build_release]
dir = ".bls"
public_dir = "docs"
entry = "blockless-codelabs.wasm"
command = "npm run build"